### PR TITLE
Don't create "webdav" directory, use selected shared folder as root

### PR DESCRIPTION
**Pull request by davidebeatrici**

### CODE REVIEW

**Comment by ryecoaaron** [comment]
Thanks!

**Comment by ryecoaaron** [comment]
Since this is a tiny change in behavior, I am not going to backport to the OMV 6.x version of the plugin.

**Comment by davidebeatrici** [comment]
No problem, thank you very much for merging so fast!

**Comment by ryecoaaron** [comment]
7.0.1 is in the repo.

**Pull request merged**
